name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Check contracts are linted
        run: yarn lint:check

      - name: Add lint summary
        run: |
          echo '## Lint results' >> $GITHUB_STEP_SUMMARY
          echo '✅ Passed' >> $GITHUB_STEP_SUMMARY

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install node
        uses: actions/setup-node@v2

      - name: Install yarn
        run: npm i -g yarn

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: yarn install

      - name: Show Foundry config
        run: forge config

      - name: Run forge tests
        run: forge test -vvv

      - name: Run hardhat tests
        run: yarn test

      - name: Add test summary
        run: |
          echo '## Test results' >> $GITHUB_STEP_SUMMARY
          echo '✅ Passed' >> $GITHUB_STEP_SUMMARY

  coverage:
    name: Run Coverage Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: forge coverage --report=summary --silent > ./summary.md
      - name: Add coverage summary
        run: |
          echo '## Coverage results' >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./summary.md)" >> $GITHUB_STEP_SUMMARY

      - run: forge coverage --report=lcov --silent > ./lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

  full-pass:
    needs:
      - 'tests'
      - 'lint'

    runs-on: ubuntu-latest

    steps:
      - name: Add summary
        run: |
          echo '## Summary' >> $GITHUB_STEP_SUMMARY
          echo '✅ All passed' >> $GITHUB_STEP_SUMMARY
